# Generated by Django 4.1.3 on 2022-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinalbum',
            name='serial_number',
            field=models.PositiveIntegerField(),
        ),
    ]
