# Generated by Django 4.1.3 on 2022-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_artist_artist_name_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
