# Generated by Django 4.1.3 on 2022-11-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id'], 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id'], 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id'], 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='songinalbum',
            options={'ordering': ['id'], 'verbose_name_plural': 'SongsInAlbum'},
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='albums', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='songinalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='app.album'),
        ),
    ]
