# Generated by Django 4.1.3 on 2022-11-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songinalbum',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='songinalbum',
            unique_together={('song', 'album')},
        ),
    ]
