# Generated by Django 4.1.3 on 2022-11-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songinalbum',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterField(
            model_name='songinalbum',
            name='serial_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
